### ISSUE TITLE
Change Dropdown Placeholder 

### ISSUE THREAD

**Issue by thiruopti** [bentorfs/angular-bootstrap-multiselect#29]
How to change the default placeholder in that dropdown?

**Comment by Duskfall** [comment]
Just had the same problem. I saw in code that there is an attribute in the directive and it works.
````
<multiselect default-text="your placeholder text here"></multiselect>

**Comment by GeethikaSJ** [comment]
It's not working.

**Comment by stand579** [comment]
I believe the `default-text` attribute never made it to a release version; however, since 1.1.5 you can use the `labels `attribute to pass a configuration object to customize all multiselect labels.  Use it like this:

```
<multiselect ng-model="selection" 
    options="options" 
    show-select-all="true"
    show-unselect-all="true" 
    labels="labels">
</multiselect>
```

and the `labels` has the following format:

```
$scope.labels = {
      itemsSelected: 'selected',
      search: 'Search...',
      select: 'Select',
      selectAll: 'Select all',
      unselectAll: 'Unselect all'
};
```
This is useful if you want to translate the labels into different languages, yet the properties are optional and if you don't define them the default multiselect labels will be displayed.
